apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudmart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nicolesoto-dev/istio-play
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
