apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudmart-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploy base first
spec:
  project: default
  source:
    repoURL: https://github.com/nicolesoto-dev/istio-play
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
