apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-svc
      version: v1
  template:
    metadata:
      labels:
        app: inventory-svc
        version: v1
    spec:
      serviceAccountName: inventory-svc
      containers:
      - name: inventory-svc
        image: hashicorp/http-echo:latest
        args: ["-text=inventory-svc-v1", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
spec:
  selector:
    app: inventory-svc
  ports:
  - port: 8080
    targetPort: 8080
