apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-svc
      version: v1
  template:
    metadata:
      labels:
        app: order-svc
        version: v1
    spec:
      serviceAccountName: order-svc
      containers:
      - name: order-svc
        image: cloudmart/order-svc:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: PRODUCT_SVC_URL
          value: "http://product-svc:8080"
        - name: PAYMENT_SVC_URL
          value: "http://payment-svc:8080"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-svc
  ports:
  - port: 8080
    targetPort: 8080
